### ISSUE TITLE
cfn-guard-rs results from guard can be string not json

### ISSUE THREAD

**Issue by kddejong** [aws-cloudformation/community-registry-extensions#60]
### Extension Name

cfn-guard-rs

### Describe the bug

Guard can return errors as strings and not as json resulting in a json parse error.

### Expected behavior

We will have to validate that the string returned is json or string.  

### Reproduction template

https://gist.github.com/benbridts/a309e1085d61795c48626a38b61da466

**Comment by benbridts** [comment]
Is it possible to catch exceptions from the rust code? It might be nice to allow the possibility to give specific errors in python.

(eg. `RuleParseError` and `DataParseError` both being subclasses of `GuardInternalError`.  In an initial version only returning a `GuardInternalError` might be fine (because more specific errors can be added later). 

I'm not sure if it would make sense to have a superclass `GuardError` or not.

**Comment by kddejong** [comment]
We have a start fix deployed for this.  Completing this for now.
